### ISSUE TITLE
If the parent element uses transform, the drag position calculation will be incorrect

### ISSUE THREAD

**Issue by yibird** [carlosjorger/fluid-dnd#54]
If the parent element uses transform, the drag position calculation will be incorrect。I am using drag and drop in a popover, which is positioned through transform. However, the calculation of the element's drag position is incorrect at this time

**Comment by yadoga** [comment]
Commenting as I've just discovered the same problem. Using Fluid-dnd in a dialog/modal that uses _transform_ for positioning.

**Comment by carlosjorger** [comment]
@yadoga In the cases I tested, the issue only appears when the transform property is given a numeric value—even zero.

**Comment by yadoga** [comment]
I may have not explained my case the best. 

The DOM hierarchy here looks like this:

- Modal (transform: translate(some_value))
   - dnd holder (here I tried to reset via additional transform: none etc.
       - fluid-dnd elements

The modal with the transform on top of the tree leads to malfunctio of the dnd

**Comment by carlosjorger** [comment]
fixed https://github.com/carlosjorger/fluid-dnd/releases/tag/v2.5.1

**Comment by yibird** [comment]
@carlosjorger  This bug still exists. The version I am using is v2.6.2
